- name: Create wsw user
  user: name="{{ wswuser }}"
        password="{{ wswpass }}"
        home="{{ homedir }}"
        shell=/bin/bash
        state=present

- name: Add authorized ssh keys for user
  authorized_key: user="{{ wswuser }}"
                  key="{{ lookup('file', 'example_key.pub') }}"

- name: Bootstrapping EPEL for CentOS
  copy: src=bootstrap-epel.repo
        dest=/etc/yum.repos.d/bootstrap-epel.repo
        owner=root
        group=root
        mode=0644
  when: ansible_distribution == 'CentOS'

- name: Installing EPEL for CentOS
  yum: name=epel-release
       state=present
       enablerepo=bootstrap-epel
  when: ansible_distribution == 'CentOS'

- name: Installing packages
  apt: pkg={{ item }}
       state=present
       update_cache=yes
  with_items:
    - s3cmd
    - supervisor
    - libcurl4-openssl-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Installing packages
  yum: name={{ item }}
       state=present
  with_items:
    - s3cmd
    - supervisor
  when: ansible_distribution == 'CentOS'

- name: Configuring supervisor for Debain / Ubuntu
  ini_file: dest=/etc/supervisor/conf.d/10.racesow.conf
            section=program:racesow
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items: supervisor_racesow
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configuring supervisor for CentOS
  ini_file: dest=/etc/supervisord.conf
            section=program:racesow
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items: supervisor_racesow
  when: ansible_distribution == 'CentOS'

- name: Configuring sudo
  template: src="99_warsow.j2"
            dest="/etc/sudoers.d/99_warsow"
            owner=root
            group=root
            mode=0440
