- name: Stopping racesow server
  command: /usr/bin/sudo supervisorctl stop racesow

- name: Updating gameserver
  sudo_user: "{{ wswuser }}"
  unarchive: src="warsow_14_unified.tar.gz"
             dest="{{ homedir }}/"

- name: Making mod directory
  file: path="{{ homedir }}/warsow_14/{{ fs_game }}"
        state=directory

- name: Making module directory
  file: path="{{ homedir }}/warsow_modules"
        state=directory

- name: Making map directory
  file: path="{{ homedir }}/warsow_maps"
        state=directory

- name: Configuring racesow server
  template: src=dedicated_autoexec.cfg.j2
            dest="{{ homedir }}/warsow_14/{{ fs_game }}/dedicated_autoexec.cfg"

- name: Configuring s3cmd
  template: src=s3cfg.j2
            dest="{{ homedir }}/.s3cfg"

- name: Syncing initial map
  command: /usr/bin/s3cmd sync s3://racesow/maps/coldrun.pk3 "{{ homedir }}/warsow_maps/"

- name: Adding mapsync cron job
  cron: name="sync maps"
        job="/usr/bin/s3cmd sync s3://racesow/maps/coldrun.pk3 {{ homedir }}/warsow_maps/"
        hour="0,6,12,18"

- name: Adding restart racesow cron job
  cron: name="restart racesow server"
        job="/usr/bin/sudo supervisorctl restart racesow"
        weekday="0"

- name: Syncing Modules
  command: /usr/bin/s3cmd sync --delete-removed s3://racesow/release/ "{{ homedir }}/warsow_modules/"

- name: Cleaning old links
  command: find "{{ homedir }}/warsow_14/{{ fs_game }}" -type l -delete

- name: Linking maps and modules
  shell: ln -s {{ homedir }}/warsow_maps/*.pk3 {{ homedir }}/warsow_modules/*.pk3 {{ homedir }}/warsow_14/{{ fs_game }}/

- name: Starting racesow server
  command: /usr/bin/sudo supervisorctl start racesow
